apiVersion: apps/v1
kind: Deployment
metadata:
  name: leiaqa-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leiaqa-api
  template:
    metadata:
      labels:
        app: leiaqa-api
    spec:
      containers:
      - name: api
        image: eslamelshamy/leiaqa-api:v6
        ports:
        - containerPort: 7049
        env:
        - name: PORT
          value: "7049"
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          value: "pg-db-svc"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "leiaqa_user"
        - name: DB_NAME
          value: "leiaqa"
        - name: REDIS_HOST
          value: "redis-db-svc"
        - name: REDIS_PORT
          value: "6379" # Hardcoded here as a string to fix the NaN error

        # Firebase
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: FIREBASE_CLIENT_EMAIL
        - name: FIREBASE_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: FIREBASE_PRIVATE_KEY
        - name: FIREBASE_DB_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: FIREBASE_DB_URL

        # Other Secrets
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PASS
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: JWT_SECRET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: SMTP_PASS
